module.exports = {
  extends: ['eslint:recommended', 'react-app'],
  parser: 'babel-eslint',
  rules: {
    'comma-dangle': ['error', 'always-multiline'],
    indent: ['error', 2, { SwitchCase: 1 }],
    'jsx-quotes': ['error', 'prefer-single'],
    'key-spacing': 'error',
    'line-comment-position': ['error', { position: 'above' }],
    'max-len': ['error', 100, 2],
    'max-lines': 'error',
    'no-console': 2,
    'no-debugger': 2,
    'no-duplicate-imports': 'error',
    'no-inline-comments': 'error',
    'no-lonely-if': 'error',
    'no-magic-numbers': ['error', { enforceConst: true }],
    'no-multi-spaces': 'error',
    'no-param-reassign': ['error'],
    'no-plusplus': 'error',
    'no-trailing-spaces': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-var': 'error',
    'object-curly-spacing': ['error', 'always'],
    'object-shorthand': ['error', 'properties'],
    'padded-blocks': ['error', 'never'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-rest-params': 'error',
    'prefer-template': 'error',
    quotes: [
      'error',
      'single',
      { avoidEscape: true, allowTemplateLiterals: true },
    ],
    'react/forbid-prop-types': 2,
    'react/jsx-boolean-value': 2,
    'react/jsx-closing-bracket-location': 2,
    'react/jsx-curly-spacing': 2,
    'react/jsx-indent-props': ['error', 2],
    'react/jsx-indent': ['error', 2],
    'react/jsx-max-props-per-line': 2,
    'react/jsx-no-duplicate-props': 2,
    'react/jsx-no-undef': 2,
    'react/jsx-sort-props': 2,
    'react/jsx-tag-spacing': ['error', { beforeSelfClosing: 'always' }],
    'react/no-danger': 2,
    'react/no-did-mount-set-state': 2,
    'react/no-multi-comp': 2,
    'react/no-unknown-property': 2,
    'react/no-unused-prop-types': 2,
    // 'react/prop-types': 2,
    'react/self-closing-comp': 2,
    'react/sort-comp': 2,
    semi: ['error', 'always', { omitLastInOneLineBlock: true }],
    'space-before-blocks': 'error',
  },
  plugins: [],
};
